- name: Mysql install
  hosts: db
  remote_user: hadrien
  become: true

  roles: 
  	- mysql

- name: ftpinstall
  hosts: db
  remote_user: hadrien
  become: true

  roles: 
  	- ftp

- name: Apache and PHP install
  hosts: web
  remote_user: hadrien
  become: true

  roles: 
  	- php

- name: Wordpress install
  hosts: web
  remote_user: hadrien
  become: true

  roles: 
  	- Wordpress	